task: 'mix_abmil'
train_data: '/features'
test_data: '/features'
output: ./output'
batch_size: 1
sample_size: 256
epochs: 160
workers: 1
loss: 'ce'
test_every: 5
weight_decay: 1.e-4
k: 32
lr: 1.e-5
image_size: 224
cuda: '1'
save_period: 1
monitor_mode: max
monitor_metric: acc
num_classes: 2
seed: 1
asynchronous: 16
feature_dim: 1024
data_num: 120